//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: NorthwindDataProxy.cs
// Generation date: 04-Jun-09 17:38:28
namespace NorthwindDb4o
{
    
    /// <summary>
    /// There are no comments for ManagementDataContext in the schema.
    /// </summary>
    public partial class ManagementDataContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ManagementDataContext object.
        /// </summary>
        public ManagementDataContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<Customer>("Customers");
                }
                return this._Customers;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Customer> _Customers;
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Category> Categories
        {
            get
            {
                if ((this._Categories == null))
                {
                    this._Categories = base.CreateQuery<Category>("Categories");
                }
                return this._Categories;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Category> _Categories;
        /// <summary>
        /// There are no comments for Suppliers in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Supplier> Suppliers
        {
            get
            {
                if ((this._Suppliers == null))
                {
                    this._Suppliers = base.CreateQuery<Supplier>("Suppliers");
                }
                return this._Suppliers;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Supplier> _Suppliers;
        /// <summary>
        /// There are no comments for Shippers in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Shipper> Shippers
        {
            get
            {
                if ((this._Shippers == null))
                {
                    this._Shippers = base.CreateQuery<Shipper>("Shippers");
                }
                return this._Shippers;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Shipper> _Shippers;
        /// <summary>
        /// There are no comments for Regions in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Region> Regions
        {
            get
            {
                if ((this._Regions == null))
                {
                    this._Regions = base.CreateQuery<Region>("Regions");
                }
                return this._Regions;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Region> _Regions;
        /// <summary>
        /// There are no comments for Employees in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Employee> Employees
        {
            get
            {
                if ((this._Employees == null))
                {
                    this._Employees = base.CreateQuery<Employee>("Employees");
                }
                return this._Employees;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Employee> _Employees;
        /// <summary>
        /// There are no comments for CustomerDemographics in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<CustomerDemographics> CustomerDemographics
        {
            get
            {
                if ((this._CustomerDemographics == null))
                {
                    this._CustomerDemographics = base.CreateQuery<CustomerDemographics>("CustomerDemographics");
                }
                return this._CustomerDemographics;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<CustomerDemographics> _CustomerDemographics;
        /// <summary>
        /// There are no comments for CustomerCustomerDemo in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<CustomerCustomerDemo> CustomerCustomerDemo
        {
            get
            {
                if ((this._CustomerCustomerDemo == null))
                {
                    this._CustomerCustomerDemo = base.CreateQuery<CustomerCustomerDemo>("CustomerCustomerDemo");
                }
                return this._CustomerCustomerDemo;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<CustomerCustomerDemo> _CustomerCustomerDemo;
        /// <summary>
        /// There are no comments for EmployeeTerritories in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<EmployeeTerritory> EmployeeTerritories
        {
            get
            {
                if ((this._EmployeeTerritories == null))
                {
                    this._EmployeeTerritories = base.CreateQuery<EmployeeTerritory>("EmployeeTerritories");
                }
                return this._EmployeeTerritories;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<EmployeeTerritory> _EmployeeTerritories;
        /// <summary>
        /// There are no comments for Territories in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Territory> Territories
        {
            get
            {
                if ((this._Territories == null))
                {
                    this._Territories = base.CreateQuery<Territory>("Territories");
                }
                return this._Territories;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Territory> _Territories;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<Product>("Products");
                }
                return this._Products;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Product> _Products;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Order> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<Order>("Orders");
                }
                return this._Orders;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Order> _Orders;
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<OrderDetail> OrderDetails
        {
            get
            {
                if ((this._OrderDetails == null))
                {
                    this._OrderDetails = base.CreateQuery<OrderDetail>("OrderDetails");
                }
                return this._OrderDetails;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<OrderDetail> _OrderDetails;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
        /// <summary>
        /// There are no comments for Suppliers in the schema.
        /// </summary>
        public void AddToSuppliers(Supplier supplier)
        {
            base.AddObject("Suppliers", supplier);
        }
        /// <summary>
        /// There are no comments for Shippers in the schema.
        /// </summary>
        public void AddToShippers(Shipper shipper)
        {
            base.AddObject("Shippers", shipper);
        }
        /// <summary>
        /// There are no comments for Regions in the schema.
        /// </summary>
        public void AddToRegions(Region region)
        {
            base.AddObject("Regions", region);
        }
        /// <summary>
        /// There are no comments for Employees in the schema.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
        /// <summary>
        /// There are no comments for CustomerDemographics in the schema.
        /// </summary>
        public void AddToCustomerDemographics(CustomerDemographics customerDemographics)
        {
            base.AddObject("CustomerDemographics", customerDemographics);
        }
        /// <summary>
        /// There are no comments for CustomerCustomerDemo in the schema.
        /// </summary>
        public void AddToCustomerCustomerDemo(CustomerCustomerDemo customerCustomerDemo)
        {
            base.AddObject("CustomerCustomerDemo", customerCustomerDemo);
        }
        /// <summary>
        /// There are no comments for EmployeeTerritories in the schema.
        /// </summary>
        public void AddToEmployeeTerritories(EmployeeTerritory employeeTerritory)
        {
            base.AddObject("EmployeeTerritories", employeeTerritory);
        }
        /// <summary>
        /// There are no comments for Territories in the schema.
        /// </summary>
        public void AddToTerritories(Territory territory)
        {
            base.AddObject("Territories", territory);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        public void AddToOrderDetails(OrderDetail orderDetail)
        {
            base.AddObject("OrderDetails", orderDetail);
        }
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CustomerID")]
    public partial class Customer
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        public static Customer CreateCustomer(string customerID)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        public string CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this._CustomerID = value;
                this.OnCustomerIDChanged();
            }
        }
        private string _CustomerID;
        partial void OnCustomerIDChanging(string value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this._CompanyName = value;
                this.OnCompanyNameChanged();
            }
        }
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property ContactName in the schema.
        /// </summary>
        public string ContactName
        {
            get
            {
                return this._ContactName;
            }
            set
            {
                this.OnContactNameChanging(value);
                this._ContactName = value;
                this.OnContactNameChanged();
            }
        }
        private string _ContactName;
        partial void OnContactNameChanging(string value);
        partial void OnContactNameChanged();
        /// <summary>
        /// There are no comments for Property ContactTitle in the schema.
        /// </summary>
        public string ContactTitle
        {
            get
            {
                return this._ContactTitle;
            }
            set
            {
                this.OnContactTitleChanging(value);
                this._ContactTitle = value;
                this.OnContactTitleChanged();
            }
        }
        private string _ContactTitle;
        partial void OnContactTitleChanging(string value);
        partial void OnContactTitleChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Region in the schema.
        /// </summary>
        public string Region
        {
            get
            {
                return this._Region;
            }
            set
            {
                this.OnRegionChanging(value);
                this._Region = value;
                this.OnRegionChanged();
            }
        }
        private string _Region;
        partial void OnRegionChanging(string value);
        partial void OnRegionChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
            }
        }
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
            }
        }
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Fax in the schema.
        /// </summary>
        public string Fax
        {
            get
            {
                return this._Fax;
            }
            set
            {
                this.OnFaxChanging(value);
                this._Fax = value;
                this.OnFaxChanged();
            }
        }
        private string _Fax;
        partial void OnFaxChanging(string value);
        partial void OnFaxChanged();
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CategoryID")]
    public partial class Category
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of CategoryID.</param>
        public static Category CreateCategory(long categoryID)
        {
            Category category = new Category();
            category.CategoryID = categoryID;
            return category;
        }
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        public long CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this._CategoryID = value;
                this.OnCategoryIDChanged();
            }
        }
        private long _CategoryID;
        partial void OnCategoryIDChanging(long value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property CategoryName in the schema.
        /// </summary>
        public string CategoryName
        {
            get
            {
                return this._CategoryName;
            }
            set
            {
                this.OnCategoryNameChanging(value);
                this._CategoryName = value;
                this.OnCategoryNameChanged();
            }
        }
        private string _CategoryName;
        partial void OnCategoryNameChanging(string value);
        partial void OnCategoryNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Picture in the schema.
        /// </summary>
        public byte[] Picture
        {
            get
            {
                if ((this._Picture != null))
                {
                    return ((byte[])(this._Picture.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPictureChanging(value);
                this._Picture = value;
                this.OnPictureChanged();
            }
        }
        private byte[] _Picture;
        partial void OnPictureChanging(byte[] value);
        partial void OnPictureChanged();
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Supplier in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SupplierID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SupplierID")]
    public partial class Supplier
    {
        /// <summary>
        /// Create a new Supplier object.
        /// </summary>
        /// <param name="supplierID">Initial value of SupplierID.</param>
        public static Supplier CreateSupplier(long supplierID)
        {
            Supplier supplier = new Supplier();
            supplier.SupplierID = supplierID;
            return supplier;
        }
        /// <summary>
        /// There are no comments for Property SupplierID in the schema.
        /// </summary>
        public long SupplierID
        {
            get
            {
                return this._SupplierID;
            }
            set
            {
                this.OnSupplierIDChanging(value);
                this._SupplierID = value;
                this.OnSupplierIDChanged();
            }
        }
        private long _SupplierID;
        partial void OnSupplierIDChanging(long value);
        partial void OnSupplierIDChanged();
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this._CompanyName = value;
                this.OnCompanyNameChanged();
            }
        }
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property ContactName in the schema.
        /// </summary>
        public string ContactName
        {
            get
            {
                return this._ContactName;
            }
            set
            {
                this.OnContactNameChanging(value);
                this._ContactName = value;
                this.OnContactNameChanged();
            }
        }
        private string _ContactName;
        partial void OnContactNameChanging(string value);
        partial void OnContactNameChanged();
        /// <summary>
        /// There are no comments for Property ContactTitle in the schema.
        /// </summary>
        public string ContactTitle
        {
            get
            {
                return this._ContactTitle;
            }
            set
            {
                this.OnContactTitleChanging(value);
                this._ContactTitle = value;
                this.OnContactTitleChanged();
            }
        }
        private string _ContactTitle;
        partial void OnContactTitleChanging(string value);
        partial void OnContactTitleChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Region in the schema.
        /// </summary>
        public string Region
        {
            get
            {
                return this._Region;
            }
            set
            {
                this.OnRegionChanging(value);
                this._Region = value;
                this.OnRegionChanged();
            }
        }
        private string _Region;
        partial void OnRegionChanging(string value);
        partial void OnRegionChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
            }
        }
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
            }
        }
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Fax in the schema.
        /// </summary>
        public string Fax
        {
            get
            {
                return this._Fax;
            }
            set
            {
                this.OnFaxChanging(value);
                this._Fax = value;
                this.OnFaxChanged();
            }
        }
        private string _Fax;
        partial void OnFaxChanging(string value);
        partial void OnFaxChanged();
        /// <summary>
        /// There are no comments for Property HomePage in the schema.
        /// </summary>
        public string HomePage
        {
            get
            {
                return this._HomePage;
            }
            set
            {
                this.OnHomePageChanging(value);
                this._HomePage = value;
                this.OnHomePageChanged();
            }
        }
        private string _HomePage;
        partial void OnHomePageChanging(string value);
        partial void OnHomePageChanged();
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Shipper in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ShipperID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ShipperID")]
    public partial class Shipper
    {
        /// <summary>
        /// Create a new Shipper object.
        /// </summary>
        /// <param name="shipperID">Initial value of ShipperID.</param>
        public static Shipper CreateShipper(long shipperID)
        {
            Shipper shipper = new Shipper();
            shipper.ShipperID = shipperID;
            return shipper;
        }
        /// <summary>
        /// There are no comments for Property ShipperID in the schema.
        /// </summary>
        public long ShipperID
        {
            get
            {
                return this._ShipperID;
            }
            set
            {
                this.OnShipperIDChanging(value);
                this._ShipperID = value;
                this.OnShipperIDChanged();
            }
        }
        private long _ShipperID;
        partial void OnShipperIDChanging(long value);
        partial void OnShipperIDChanged();
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this._CompanyName = value;
                this.OnCompanyNameChanged();
            }
        }
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Region in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RegionID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("RegionID")]
    public partial class Region
    {
        /// <summary>
        /// Create a new Region object.
        /// </summary>
        /// <param name="regionID">Initial value of RegionID.</param>
        public static Region CreateRegion(long regionID)
        {
            Region region = new Region();
            region.RegionID = regionID;
            return region;
        }
        /// <summary>
        /// There are no comments for Property RegionID in the schema.
        /// </summary>
        public long RegionID
        {
            get
            {
                return this._RegionID;
            }
            set
            {
                this.OnRegionIDChanging(value);
                this._RegionID = value;
                this.OnRegionIDChanged();
            }
        }
        private long _RegionID;
        partial void OnRegionIDChanging(long value);
        partial void OnRegionIDChanged();
        /// <summary>
        /// There are no comments for Property RegionDescription in the schema.
        /// </summary>
        public string RegionDescription
        {
            get
            {
                return this._RegionDescription;
            }
            set
            {
                this.OnRegionDescriptionChanging(value);
                this._RegionDescription = value;
                this.OnRegionDescriptionChanged();
            }
        }
        private string _RegionDescription;
        partial void OnRegionDescriptionChanging(string value);
        partial void OnRegionDescriptionChanged();
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EmployeeID")]
    public partial class Employee
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employeeID">Initial value of EmployeeID.</param>
        /// <param name="birthDate">Initial value of BirthDate.</param>
        /// <param name="hireDate">Initial value of HireDate.</param>
        public static Employee CreateEmployee(long employeeID, global::System.DateTime birthDate, global::System.DateTime hireDate)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            employee.BirthDate = birthDate;
            employee.HireDate = hireDate;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property EmployeeID in the schema.
        /// </summary>
        public long EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this._EmployeeID = value;
                this.OnEmployeeIDChanged();
            }
        }
        private long _EmployeeID;
        partial void OnEmployeeIDChanging(long value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property TitleOfCourtesy in the schema.
        /// </summary>
        public string TitleOfCourtesy
        {
            get
            {
                return this._TitleOfCourtesy;
            }
            set
            {
                this.OnTitleOfCourtesyChanging(value);
                this._TitleOfCourtesy = value;
                this.OnTitleOfCourtesyChanged();
            }
        }
        private string _TitleOfCourtesy;
        partial void OnTitleOfCourtesyChanging(string value);
        partial void OnTitleOfCourtesyChanged();
        /// <summary>
        /// There are no comments for Property BirthDate in the schema.
        /// </summary>
        public global::System.DateTime BirthDate
        {
            get
            {
                return this._BirthDate;
            }
            set
            {
                this.OnBirthDateChanging(value);
                this._BirthDate = value;
                this.OnBirthDateChanged();
            }
        }
        private global::System.DateTime _BirthDate;
        partial void OnBirthDateChanging(global::System.DateTime value);
        partial void OnBirthDateChanged();
        /// <summary>
        /// There are no comments for Property HireDate in the schema.
        /// </summary>
        public global::System.DateTime HireDate
        {
            get
            {
                return this._HireDate;
            }
            set
            {
                this.OnHireDateChanging(value);
                this._HireDate = value;
                this.OnHireDateChanged();
            }
        }
        private global::System.DateTime _HireDate;
        partial void OnHireDateChanging(global::System.DateTime value);
        partial void OnHireDateChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Region in the schema.
        /// </summary>
        public string Region
        {
            get
            {
                return this._Region;
            }
            set
            {
                this.OnRegionChanging(value);
                this._Region = value;
                this.OnRegionChanged();
            }
        }
        private string _Region;
        partial void OnRegionChanging(string value);
        partial void OnRegionChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
            }
        }
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
            }
        }
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property HomePhone in the schema.
        /// </summary>
        public string HomePhone
        {
            get
            {
                return this._HomePhone;
            }
            set
            {
                this.OnHomePhoneChanging(value);
                this._HomePhone = value;
                this.OnHomePhoneChanged();
            }
        }
        private string _HomePhone;
        partial void OnHomePhoneChanging(string value);
        partial void OnHomePhoneChanged();
        /// <summary>
        /// There are no comments for Property Extension in the schema.
        /// </summary>
        public string Extension
        {
            get
            {
                return this._Extension;
            }
            set
            {
                this.OnExtensionChanging(value);
                this._Extension = value;
                this.OnExtensionChanged();
            }
        }
        private string _Extension;
        partial void OnExtensionChanging(string value);
        partial void OnExtensionChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
            }
        }
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Photo in the schema.
        /// </summary>
        public byte[] Photo
        {
            get
            {
                if ((this._Photo != null))
                {
                    return ((byte[])(this._Photo.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPhotoChanging(value);
                this._Photo = value;
                this.OnPhotoChanged();
            }
        }
        private byte[] _Photo;
        partial void OnPhotoChanging(byte[] value);
        partial void OnPhotoChanged();
        /// <summary>
        /// There are no comments for Property PhotoPath in the schema.
        /// </summary>
        public string PhotoPath
        {
            get
            {
                return this._PhotoPath;
            }
            set
            {
                this.OnPhotoPathChanging(value);
                this._PhotoPath = value;
                this.OnPhotoPathChanged();
            }
        }
        private string _PhotoPath;
        partial void OnPhotoPathChanging(string value);
        partial void OnPhotoPathChanged();
        /// <summary>
        /// There are no comments for ReportsTo in the schema.
        /// </summary>
        public Employee ReportsTo
        {
            get
            {
                return this._ReportsTo;
            }
            set
            {
                this._ReportsTo = value;
            }
        }
        private Employee _ReportsTo;
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.CustomerDemographics in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CustomerTypeID")]
    public partial class CustomerDemographics
    {
        /// <summary>
        /// Create a new CustomerDemographics object.
        /// </summary>
        /// <param name="customerTypeID">Initial value of CustomerTypeID.</param>
        public static CustomerDemographics CreateCustomerDemographics(string customerTypeID)
        {
            CustomerDemographics customerDemographics = new CustomerDemographics();
            customerDemographics.CustomerTypeID = customerTypeID;
            return customerDemographics;
        }
        /// <summary>
        /// There are no comments for Property CustomerTypeID in the schema.
        /// </summary>
        public string CustomerTypeID
        {
            get
            {
                return this._CustomerTypeID;
            }
            set
            {
                this.OnCustomerTypeIDChanging(value);
                this._CustomerTypeID = value;
                this.OnCustomerTypeIDChanged();
            }
        }
        private string _CustomerTypeID;
        partial void OnCustomerTypeIDChanging(string value);
        partial void OnCustomerTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CustomerDesc in the schema.
        /// </summary>
        public string CustomerDesc
        {
            get
            {
                return this._CustomerDesc;
            }
            set
            {
                this.OnCustomerDescChanging(value);
                this._CustomerDesc = value;
                this.OnCustomerDescChanged();
            }
        }
        private string _CustomerDesc;
        partial void OnCustomerDescChanging(string value);
        partial void OnCustomerDescChanged();
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.CustomerCustomerDemo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerCustomerDemoID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CustomerCustomerDemoID")]
    public partial class CustomerCustomerDemo
    {
        /// <summary>
        /// Create a new CustomerCustomerDemo object.
        /// </summary>
        /// <param name="customerCustomerDemoID">Initial value of CustomerCustomerDemoID.</param>
        public static CustomerCustomerDemo CreateCustomerCustomerDemo(string customerCustomerDemoID)
        {
            CustomerCustomerDemo customerCustomerDemo = new CustomerCustomerDemo();
            customerCustomerDemo.CustomerCustomerDemoID = customerCustomerDemoID;
            return customerCustomerDemo;
        }
        /// <summary>
        /// There are no comments for Property CustomerCustomerDemoID in the schema.
        /// </summary>
        public string CustomerCustomerDemoID
        {
            get
            {
                return this._CustomerCustomerDemoID;
            }
            set
            {
                this.OnCustomerCustomerDemoIDChanging(value);
                this._CustomerCustomerDemoID = value;
                this.OnCustomerCustomerDemoIDChanged();
            }
        }
        private string _CustomerCustomerDemoID;
        partial void OnCustomerCustomerDemoIDChanging(string value);
        partial void OnCustomerCustomerDemoIDChanged();
        /// <summary>
        /// There are no comments for CustomerTypeID in the schema.
        /// </summary>
        public CustomerDemographics CustomerTypeID
        {
            get
            {
                return this._CustomerTypeID;
            }
            set
            {
                this._CustomerTypeID = value;
            }
        }
        private CustomerDemographics _CustomerTypeID;
        /// <summary>
        /// There are no comments for CustomerID in the schema.
        /// </summary>
        public Customer CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this._CustomerID = value;
            }
        }
        private Customer _CustomerID;
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.EmployeeTerritory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeTerritoryID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EmployeeTerritoryID")]
    public partial class EmployeeTerritory
    {
        /// <summary>
        /// Create a new EmployeeTerritory object.
        /// </summary>
        /// <param name="employeeTerritoryID">Initial value of EmployeeTerritoryID.</param>
        public static EmployeeTerritory CreateEmployeeTerritory(string employeeTerritoryID)
        {
            EmployeeTerritory employeeTerritory = new EmployeeTerritory();
            employeeTerritory.EmployeeTerritoryID = employeeTerritoryID;
            return employeeTerritory;
        }
        /// <summary>
        /// There are no comments for Property EmployeeTerritoryID in the schema.
        /// </summary>
        public string EmployeeTerritoryID
        {
            get
            {
                return this._EmployeeTerritoryID;
            }
            set
            {
                this.OnEmployeeTerritoryIDChanging(value);
                this._EmployeeTerritoryID = value;
                this.OnEmployeeTerritoryIDChanged();
            }
        }
        private string _EmployeeTerritoryID;
        partial void OnEmployeeTerritoryIDChanging(string value);
        partial void OnEmployeeTerritoryIDChanged();
        /// <summary>
        /// There are no comments for EmployeeID in the schema.
        /// </summary>
        public Employee EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this._EmployeeID = value;
            }
        }
        private Employee _EmployeeID;
        /// <summary>
        /// There are no comments for TerritoryID in the schema.
        /// </summary>
        public Territory TerritoryID
        {
            get
            {
                return this._TerritoryID;
            }
            set
            {
                this._TerritoryID = value;
            }
        }
        private Territory _TerritoryID;
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Territory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TerritoryID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TerritoryID")]
    public partial class Territory
    {
        /// <summary>
        /// Create a new Territory object.
        /// </summary>
        /// <param name="territoryID">Initial value of TerritoryID.</param>
        public static Territory CreateTerritory(string territoryID)
        {
            Territory territory = new Territory();
            territory.TerritoryID = territoryID;
            return territory;
        }
        /// <summary>
        /// There are no comments for Property TerritoryID in the schema.
        /// </summary>
        public string TerritoryID
        {
            get
            {
                return this._TerritoryID;
            }
            set
            {
                this.OnTerritoryIDChanging(value);
                this._TerritoryID = value;
                this.OnTerritoryIDChanged();
            }
        }
        private string _TerritoryID;
        partial void OnTerritoryIDChanging(string value);
        partial void OnTerritoryIDChanged();
        /// <summary>
        /// There are no comments for Property TerritoryDescription in the schema.
        /// </summary>
        public string TerritoryDescription
        {
            get
            {
                return this._TerritoryDescription;
            }
            set
            {
                this.OnTerritoryDescriptionChanging(value);
                this._TerritoryDescription = value;
                this.OnTerritoryDescriptionChanged();
            }
        }
        private string _TerritoryDescription;
        partial void OnTerritoryDescriptionChanging(string value);
        partial void OnTerritoryDescriptionChanged();
        /// <summary>
        /// There are no comments for RegionID in the schema.
        /// </summary>
        public Region RegionID
        {
            get
            {
                return this._RegionID;
            }
            set
            {
                this._RegionID = value;
            }
        }
        private Region _RegionID;
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductID")]
    public partial class Product
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="unitPrice">Initial value of UnitPrice.</param>
        /// <param name="unitsInStock">Initial value of UnitsInStock.</param>
        /// <param name="unitsOnOrder">Initial value of UnitsOnOrder.</param>
        /// <param name="reorderLevel">Initial value of ReorderLevel.</param>
        /// <param name="discontinued">Initial value of Discontinued.</param>
        public static Product CreateProduct(long productID, double unitPrice, int unitsInStock, int unitsOnOrder, int reorderLevel, bool discontinued)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.UnitPrice = unitPrice;
            product.UnitsInStock = unitsInStock;
            product.UnitsOnOrder = unitsOnOrder;
            product.ReorderLevel = reorderLevel;
            product.Discontinued = discontinued;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        public long ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
            }
        }
        private long _ProductID;
        partial void OnProductIDChanging(long value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
            }
        }
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property QuantityPerUnit in the schema.
        /// </summary>
        public string QuantityPerUnit
        {
            get
            {
                return this._QuantityPerUnit;
            }
            set
            {
                this.OnQuantityPerUnitChanging(value);
                this._QuantityPerUnit = value;
                this.OnQuantityPerUnitChanged();
            }
        }
        private string _QuantityPerUnit;
        partial void OnQuantityPerUnitChanging(string value);
        partial void OnQuantityPerUnitChanged();
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        public double UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
            }
        }
        private double _UnitPrice;
        partial void OnUnitPriceChanging(double value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// There are no comments for Property UnitsInStock in the schema.
        /// </summary>
        public int UnitsInStock
        {
            get
            {
                return this._UnitsInStock;
            }
            set
            {
                this.OnUnitsInStockChanging(value);
                this._UnitsInStock = value;
                this.OnUnitsInStockChanged();
            }
        }
        private int _UnitsInStock;
        partial void OnUnitsInStockChanging(int value);
        partial void OnUnitsInStockChanged();
        /// <summary>
        /// There are no comments for Property UnitsOnOrder in the schema.
        /// </summary>
        public int UnitsOnOrder
        {
            get
            {
                return this._UnitsOnOrder;
            }
            set
            {
                this.OnUnitsOnOrderChanging(value);
                this._UnitsOnOrder = value;
                this.OnUnitsOnOrderChanged();
            }
        }
        private int _UnitsOnOrder;
        partial void OnUnitsOnOrderChanging(int value);
        partial void OnUnitsOnOrderChanged();
        /// <summary>
        /// There are no comments for Property ReorderLevel in the schema.
        /// </summary>
        public int ReorderLevel
        {
            get
            {
                return this._ReorderLevel;
            }
            set
            {
                this.OnReorderLevelChanging(value);
                this._ReorderLevel = value;
                this.OnReorderLevelChanged();
            }
        }
        private int _ReorderLevel;
        partial void OnReorderLevelChanging(int value);
        partial void OnReorderLevelChanged();
        /// <summary>
        /// There are no comments for Property Discontinued in the schema.
        /// </summary>
        public bool Discontinued
        {
            get
            {
                return this._Discontinued;
            }
            set
            {
                this.OnDiscontinuedChanging(value);
                this._Discontinued = value;
                this.OnDiscontinuedChanged();
            }
        }
        private bool _Discontinued;
        partial void OnDiscontinuedChanging(bool value);
        partial void OnDiscontinuedChanged();
        /// <summary>
        /// There are no comments for SupplierID in the schema.
        /// </summary>
        public Supplier SupplierID
        {
            get
            {
                return this._SupplierID;
            }
            set
            {
                this._SupplierID = value;
            }
        }
        private Supplier _SupplierID;
        /// <summary>
        /// There are no comments for CategoryID in the schema.
        /// </summary>
        public Category CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this._CategoryID = value;
            }
        }
        private Category _CategoryID;
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OrderID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("OrderID")]
    public partial class Order
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderID">Initial value of OrderID.</param>
        /// <param name="orderDate">Initial value of OrderDate.</param>
        /// <param name="requiredDate">Initial value of RequiredDate.</param>
        /// <param name="shippedDate">Initial value of ShippedDate.</param>
        /// <param name="freight">Initial value of Freight.</param>
        public static Order CreateOrder(long orderID, global::System.DateTime orderDate, global::System.DateTime requiredDate, global::System.DateTime shippedDate, double freight)
        {
            Order order = new Order();
            order.OrderID = orderID;
            order.OrderDate = orderDate;
            order.RequiredDate = requiredDate;
            order.ShippedDate = shippedDate;
            order.Freight = freight;
            return order;
        }
        /// <summary>
        /// There are no comments for Property OrderID in the schema.
        /// </summary>
        public long OrderID
        {
            get
            {
                return this._OrderID;
            }
            set
            {
                this.OnOrderIDChanging(value);
                this._OrderID = value;
                this.OnOrderIDChanged();
            }
        }
        private long _OrderID;
        partial void OnOrderIDChanging(long value);
        partial void OnOrderIDChanged();
        /// <summary>
        /// There are no comments for Property OrderDate in the schema.
        /// </summary>
        public global::System.DateTime OrderDate
        {
            get
            {
                return this._OrderDate;
            }
            set
            {
                this.OnOrderDateChanging(value);
                this._OrderDate = value;
                this.OnOrderDateChanged();
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
        /// <summary>
        /// There are no comments for Property RequiredDate in the schema.
        /// </summary>
        public global::System.DateTime RequiredDate
        {
            get
            {
                return this._RequiredDate;
            }
            set
            {
                this.OnRequiredDateChanging(value);
                this._RequiredDate = value;
                this.OnRequiredDateChanged();
            }
        }
        private global::System.DateTime _RequiredDate;
        partial void OnRequiredDateChanging(global::System.DateTime value);
        partial void OnRequiredDateChanged();
        /// <summary>
        /// There are no comments for Property ShippedDate in the schema.
        /// </summary>
        public global::System.DateTime ShippedDate
        {
            get
            {
                return this._ShippedDate;
            }
            set
            {
                this.OnShippedDateChanging(value);
                this._ShippedDate = value;
                this.OnShippedDateChanged();
            }
        }
        private global::System.DateTime _ShippedDate;
        partial void OnShippedDateChanging(global::System.DateTime value);
        partial void OnShippedDateChanged();
        /// <summary>
        /// There are no comments for Property Freight in the schema.
        /// </summary>
        public double Freight
        {
            get
            {
                return this._Freight;
            }
            set
            {
                this.OnFreightChanging(value);
                this._Freight = value;
                this.OnFreightChanged();
            }
        }
        private double _Freight;
        partial void OnFreightChanging(double value);
        partial void OnFreightChanged();
        /// <summary>
        /// There are no comments for Property ShipName in the schema.
        /// </summary>
        public string ShipName
        {
            get
            {
                return this._ShipName;
            }
            set
            {
                this.OnShipNameChanging(value);
                this._ShipName = value;
                this.OnShipNameChanged();
            }
        }
        private string _ShipName;
        partial void OnShipNameChanging(string value);
        partial void OnShipNameChanged();
        /// <summary>
        /// There are no comments for Property ShipAddress in the schema.
        /// </summary>
        public string ShipAddress
        {
            get
            {
                return this._ShipAddress;
            }
            set
            {
                this.OnShipAddressChanging(value);
                this._ShipAddress = value;
                this.OnShipAddressChanged();
            }
        }
        private string _ShipAddress;
        partial void OnShipAddressChanging(string value);
        partial void OnShipAddressChanged();
        /// <summary>
        /// There are no comments for Property ShipCity in the schema.
        /// </summary>
        public string ShipCity
        {
            get
            {
                return this._ShipCity;
            }
            set
            {
                this.OnShipCityChanging(value);
                this._ShipCity = value;
                this.OnShipCityChanged();
            }
        }
        private string _ShipCity;
        partial void OnShipCityChanging(string value);
        partial void OnShipCityChanged();
        /// <summary>
        /// There are no comments for Property ShipRegion in the schema.
        /// </summary>
        public string ShipRegion
        {
            get
            {
                return this._ShipRegion;
            }
            set
            {
                this.OnShipRegionChanging(value);
                this._ShipRegion = value;
                this.OnShipRegionChanged();
            }
        }
        private string _ShipRegion;
        partial void OnShipRegionChanging(string value);
        partial void OnShipRegionChanged();
        /// <summary>
        /// There are no comments for Property ShipPostalCode in the schema.
        /// </summary>
        public string ShipPostalCode
        {
            get
            {
                return this._ShipPostalCode;
            }
            set
            {
                this.OnShipPostalCodeChanging(value);
                this._ShipPostalCode = value;
                this.OnShipPostalCodeChanged();
            }
        }
        private string _ShipPostalCode;
        partial void OnShipPostalCodeChanging(string value);
        partial void OnShipPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property ShipCountry in the schema.
        /// </summary>
        public string ShipCountry
        {
            get
            {
                return this._ShipCountry;
            }
            set
            {
                this.OnShipCountryChanging(value);
                this._ShipCountry = value;
                this.OnShipCountryChanged();
            }
        }
        private string _ShipCountry;
        partial void OnShipCountryChanging(string value);
        partial void OnShipCountryChanged();
        /// <summary>
        /// There are no comments for CustomerID in the schema.
        /// </summary>
        public Customer CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this._CustomerID = value;
            }
        }
        private Customer _CustomerID;
        /// <summary>
        /// There are no comments for EmployeeID in the schema.
        /// </summary>
        public Employee EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this._EmployeeID = value;
            }
        }
        private Employee _EmployeeID;
        /// <summary>
        /// There are no comments for ShipVia in the schema.
        /// </summary>
        public Shipper ShipVia
        {
            get
            {
                return this._ShipVia;
            }
            set
            {
                this._ShipVia = value;
            }
        }
        private Shipper _ShipVia;
    }
    /// <summary>
    /// There are no comments for NorthwindDb4o.OrderDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OrderDetailID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("OrderDetailID")]
    public partial class OrderDetail
    {
        /// <summary>
        /// Create a new OrderDetail object.
        /// </summary>
        /// <param name="orderDetailID">Initial value of OrderDetailID.</param>
        /// <param name="unitPrice">Initial value of UnitPrice.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="discount">Initial value of Discount.</param>
        public static OrderDetail CreateOrderDetail(string orderDetailID, double unitPrice, int quantity, double discount)
        {
            OrderDetail orderDetail = new OrderDetail();
            orderDetail.OrderDetailID = orderDetailID;
            orderDetail.UnitPrice = unitPrice;
            orderDetail.Quantity = quantity;
            orderDetail.Discount = discount;
            return orderDetail;
        }
        /// <summary>
        /// There are no comments for Property OrderDetailID in the schema.
        /// </summary>
        public string OrderDetailID
        {
            get
            {
                return this._OrderDetailID;
            }
            set
            {
                this.OnOrderDetailIDChanging(value);
                this._OrderDetailID = value;
                this.OnOrderDetailIDChanged();
            }
        }
        private string _OrderDetailID;
        partial void OnOrderDetailIDChanging(string value);
        partial void OnOrderDetailIDChanged();
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        public double UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
            }
        }
        private double _UnitPrice;
        partial void OnUnitPriceChanging(double value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
            }
        }
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Discount in the schema.
        /// </summary>
        public double Discount
        {
            get
            {
                return this._Discount;
            }
            set
            {
                this.OnDiscountChanging(value);
                this._Discount = value;
                this.OnDiscountChanged();
            }
        }
        private double _Discount;
        partial void OnDiscountChanging(double value);
        partial void OnDiscountChanged();
        /// <summary>
        /// There are no comments for OrderID in the schema.
        /// </summary>
        public Order OrderID
        {
            get
            {
                return this._OrderID;
            }
            set
            {
                this._OrderID = value;
            }
        }
        private Order _OrderID;
        /// <summary>
        /// There are no comments for ProductID in the schema.
        /// </summary>
        public Product ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this._ProductID = value;
            }
        }
        private Product _ProductID;
    }
}
